### ISSUE TITLE
hot-update files not found

### ISSUE THREAD

**Issue by jestho** [satya164/quik#2]
When I use `quik -w index.js` and make changes to my components (eg. `./MyComponent.js` or `./components/Test.js` (imported from `./Mycomponent.js`)), I get the following error:

```
<-- GET /189a6a414e86fb2b35b8.hot-update.json
  --> GET /189a6a414e86fb2b35b8.hot-update.json 200 1ms 36b
  <-- GET /0.189a6a414e86fb2b35b8.hot-update.js
  xxx GET /0.189a6a414e86fb2b35b8.hot-update.js 500 1ms -

  Error: File not found: /Users/jesthoge/Desktop/prototype/0.189a6a414e86fb2b35b8.hot-update.js
      at /usr/local/lib/node_modules/quik/src/configure.js:24:28
      at FSReqWrap.cb [as oncomplete] (fs.js:216:19)
```

Tested with node version `5.0.0`, `5.2.0` and `5.3.0`.

Update: Seems to be working if I pull the repo and run `bin/quik.js`. Is the npm version out of date?

**Comment by satya164** [comment]
@jestho Hey thanks for the report. I've not published the latest changes to npm. Was writing some tests first. Will publish tonight.

**Comment by jestho** [comment]
Awesome! Great project, btw. No more config-madness for simple prototyping 😊

**Comment by satya164** [comment]
@jestho Thank you :)

I published to npm. Can you test if it works now?

**Comment by jestho** [comment]
Works!

**Comment by satya164** [comment]
@jestho Awesome. Thanks :D
