### ISSUE TITLE
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "base" at 0

### ISSUE THREAD

**Issue by Pathsofdesign** [satya164/quik#21]
Hey there, I'm trying out `quik` this morning and absolutely love the concept. However, I'm not able to get it running. I've installed quik and then added a index.js file to a directory and ran the quik command and receive the following error:

Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to "/Users/andrewdelprete/Work/Code Testing/quik-test"

Do I need to install `npm transform-runtime -g` perhaps? Thank you!

**Comment by RafalFilipek** [comment]
I think it might be connected with `.babelrc` / `babelrc.js` and global installation.
Quik is working just fine if installed locally (without `-g` flag).
It might be problem with Babel, but it's just an idea.

**Comment by satya164** [comment]
@Pathsofdesign Hey. Not sure why it's not working. Have you tried uninstalling and re-installing `quik`?

Will have a proper look at this tomorrow. For now you can do `npm install transform-runtime` in the project directory.

**Comment by satya164** [comment]
I just published a new release which should fix the issue. Please try it out and let me know.

**Comment by Pathsofdesign** [comment]
Thank you very much for the response, if I knew what I was doing I would have tried to fix it myself. I'll have a look this afternoon and let you know!

**Comment by satya164** [comment]
@Pathsofdesign Did you try?

**Comment by Pathsofdesign** [comment]
This is working now, thank you!

**Comment by shaponpal6** [comment]
**Use cmd as administrator Mode.**

It's worked for me

Enjoy!
