### ISSUE TITLE
Super heavy packaging

### ISSUE THREAD

**Issue by jaimeagudo** [satya164/quik#260]
Just doing 

```
$ cd template
$ quik
```

I see on the network tab the index.js is **2.2MB**

![screen shot 2017-04-20 at 15 41 49](https://cloud.githubusercontent.com/assets/4053914/25233724/243178fc-25e0-11e7-90e0-fc44d0ee66f9.png)

Am I missing something?

**Comment by satya164** [comment]
This is development build + sourcemaps are inlined. Production bundle is much smaller.

**Comment by jaimeagudo** [comment]
Thanks for your fast reply 👍 . I guessed that (it seems a lot anyway) but was just asking cause this

`quik --html --output out.html --production` produces a 2.4MB out.html file so I thought there was some wrong root on my side

**Comment by satya164** [comment]
@jaimeagudo it's because the sourcemap is inlined. try with `--sourcemaps false`

**Comment by jaimeagudo** [comment]
That's my point :)

Obviously a `--production` build _should_ remove the `sourcemaps`, I encourage you to change `--production` behaviour my dear friend :)

Thanks for sharing
