### ISSUE TITLE
Remove default packages?

### ISSUE THREAD

**Issue by jestho** [satya164/quik#6]
Default packages seems a bit redundant now that `npm-install-loader` has been added, don't you think?

**Comment by satya164** [comment]
@jestho Yeah, but still it's useful, because you don't have to wait for npm install to complete to be able to try something. You can get started right away. For example I've a slow connection, and I never wanna npm install :)

**Comment by jestho** [comment]
You've got a point about slow connections. However, now that a new version of `redux-simple-router` is getting released, I'd rather not wait for you (sorry ;)) to update Quik. Seems like it might be a hassle to maintain this in the long run. Might it be possible to override the defaults with the locally installed modules?

**Comment by satya164** [comment]
@jestho You can install the package locally. It should just use your local version if you have it locally, and only fallback to the bundled one if you don't have it. I've not tested this though.

BTW I've configured greenkeeper for this repo, which automatically sends PRs when a dep is updated.

**Comment by satya164** [comment]
Lemme know if you face any issues.

**Comment by jestho** [comment]
If that's the case, I apologize. It's been a long day... :)

**Comment by satya164** [comment]
@jestho No problem. It's always better to discuss the usecases and possible pitfalls. Feel free to report issues for any concerns you've.
