### ISSUE TITLE
Webpack v2.1.0-beta.23 and later breaks quik

### ISSUE THREAD

**Issue by bsiepert** [satya164/quik#81]
If you refer to https://github.com/webpack/webpack/issues/3018 , it seems there was a breaking change in how webpack validates configuration objects. I was able to get quik to work by forcing it to use v2.1.0-beta.22, however a smarter person than I will have to figure out how to adjust how quick is using webpack's configuration object.

**Comment by satya164** [comment]
@bsiepert Thanks for the report. I'll investigate ASAP.

**Comment by felippenardi** [comment]
@bsiepert Meanwhile, how did you force it to use v2.1.0-beta.22?

**Comment by bsiepert** [comment]
@felippenardi see the diff in the linked pull request. In short you just need to edit quik's package.json line for webpack and remove the carat at the beginning of the line to change
`"webpack": "^2.1.0-beta.22",`
to
`"webpack": "2.1.0-beta.22",`

**Comment by felippenardi** [comment]
@bsiepert How do I generate a distribution version after modifying it?

**Comment by MrSkinny** [comment]
@bsiepert How did you force Quik to use beta.22?

**Comment by bsiepert** [comment]
I'm not sure what you mean by "generate a distribution version"; in my case I modified the package.json in place wherever quik got installed , probably did an npm install and things worked.

**Comment by MrSkinny** [comment]
@bsiepert I tried that and ran `npm install` but it failed on trying to recreate the `dist` folder saying that `src` doesn't exist.  Now `quik` from the CL doesn't run at all.

**Comment by MrSkinny** [comment]
Fyi @felippenardi this is probably a really unintuitive way to do it, but I just grabbed the `quik` source from this repo and put it in a temp folder, changed the webpack version in `package.json`, then ran `npm install`.  Then I copied the resulting `bin/` `dist/` and `node_modules/` folders into the globally installed version.  Now it appears to working without an error!

**Comment by satya164** [comment]
sorry for not looking into this issue. just a little busy with work an other things. for now it's hardcoded (thanks @bsiepert ), I'll take a look when I get time.

If anyone has time to take a look, it'll be great!

**Comment by satya164** [comment]
Fixed by 08fe9fd8a5dc93851af29ece7f360ef7e9ac49c9
